#! /bin/bash
#  author fengxp
#  time  2016-05-24 
#  program : 判断进行是否存在，并重新启动


function check(){
    count=`ps -ef |grep $1 |grep -v "grep" |wc -l`
    echo $count
    if [ 0 == $count ];then
    	date >> /root/checkStart.log
	/sbin/reboot
#	/var/eadv/chromStart &
    fi
}
check chromium-browser
